# Generated by Django 4.1.3 on 2022-11-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('dataReserva', models.DateField(help_text='Data da Reserva')),
                ('obs', models.CharField(primary_key=True, serialize=False, help_text='Insira o motivo da reserva', max_length=300)),
            ],
        ),
    ]
